### recover all movies
GET http://localhost:1234/movies

### recover movie by id
GET http://localhost:1234/movies/4e152ba8-15c3-4570-a0b7-f794125e0a60

### recover movie by genre
GET http://localhost:1234/movies?genre=Crime

### recover movie by search
GET http://localhost:1234/movies?search=christophER Nolan

### recover movie by search + genre
GET http://localhost:1234/movies?search=christophER Nolan&genre=Sci-Fi

### create movie - (rate is optional)
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1901,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
        "Drama"
    ]
}

### partially update a movie
PATCH http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf
Content-Type: application/json

{
    "title": "TEST andres"
}


### delete a movie
DELETE http://localhost:1234/movies/3de1a888-d6ea-4da1-9f6d-925eea0d29ce